package com.lanny.spring_security_template.infrastructure.web.common.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.Instant;
import java.util.Map;

/**
 * Standardized error response following RFC 9457 Problem Details for HTTP APIs.
 *
 * <p>This DTO provides a consistent error format across all API endpoints, making it easier
 * for clients to handle errors predictably.
 *
 * <p>RFC 9457 defines a "problem detail" as a way to carry machine-readable details of errors
 * in HTTP response content. It includes:
 * <ul>
 *   <li>type: URI reference identifying the problem type</li>
 *   <li>title: Short, human-readable summary</li>
 *   <li>status: HTTP status code</li>
 *   <li>detail: Human-readable explanation specific to this occurrence</li>
 *   <li>instance: URI reference identifying the specific occurrence</li>
 * </ul>
 *
 * @see <a href="https://www.rfc-editor.org/rfc/rfc9457.html">RFC 9457 - Problem Details for HTTP APIs</a>
 */
@Schema(
    name = "ErrorResponse",
    description = "Standardized error response following RFC 9457 Problem Details for HTTP APIs",
    example = """
        {
          "type": "about:blank",
          "title": "Unauthorized",
          "status": 401,
          "detail": "Invalid or expired JWT token",
          "instance": "/api/v1/users",
          "timestamp": "2025-12-26T18:30:00Z",
          "errors": {
            "token": "Token signature verification failed"
          }
        }
        """
)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ErrorResponse(

    @Schema(
        description = "URI reference identifying the problem type. Use 'about:blank' for generic errors.",
        example = "about:blank",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    String type,

    @Schema(
        description = "Short, human-readable summary of the problem type. Should not change between occurrences.",
        example = "Unauthorized",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    String title,

    @Schema(
        description = "HTTP status code generated by the origin server for this occurrence.",
        example = "401",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    int status,

    @Schema(
        description = "Human-readable explanation specific to this occurrence of the problem.",
        example = "Invalid or expired JWT token",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    String detail,

    @Schema(
        description = "URI reference identifying the specific occurrence of the problem (typically the request path).",
        example = "/api/v1/users",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    String instance,

    @Schema(
        description = "Timestamp when the error occurred (ISO-8601 UTC format).",
        example = "2025-12-26T18:30:00Z",
        type = "string",
        format = "date-time"
    )
    Instant timestamp,

    @Schema(
        description = "Additional error details, validation errors, or field-specific errors.",
        example = "{\"username\": \"Username is already taken\", \"email\": \"Invalid email format\"}",
        nullable = true
    )
    Map<String, String> errors
) {

    /**
     * Creates an error response without additional error details.
     */
    public ErrorResponse(String type, String title, int status, String detail, String instance) {
        this(type, title, status, detail, instance, Instant.now(), null);
    }

    /**
     * Creates an error response with field-specific validation errors.
     */
    public ErrorResponse(String type, String title, int status, String detail, String instance, Map<String, String> errors) {
        this(type, title, status, detail, instance, Instant.now(), errors);
    }

    /**
     * Creates a simple error response with minimal details.
     */
    public static ErrorResponse of(int status, String title, String detail, String instance) {
        return new ErrorResponse("about:blank", title, status, detail, instance);
    }

    /**
     * Creates a 400 Bad Request error response.
     */
    public static ErrorResponse badRequest(String detail, String instance) {
        return new ErrorResponse("about:blank", "Bad Request", 400, detail, instance);
    }

    /**
     * Creates a 400 Bad Request error response with validation errors.
     */
    public static ErrorResponse badRequest(String detail, String instance, Map<String, String> errors) {
        return new ErrorResponse("about:blank", "Bad Request", 400, detail, instance, errors);
    }

    /**
     * Creates a 401 Unauthorized error response.
     */
    public static ErrorResponse unauthorized(String detail, String instance) {
        return new ErrorResponse("about:blank", "Unauthorized", 401, detail, instance);
    }

    /**
     * Creates a 403 Forbidden error response.
     */
    public static ErrorResponse forbidden(String detail, String instance) {
        return new ErrorResponse("about:blank", "Forbidden", 403, detail, instance);
    }

    /**
     * Creates a 404 Not Found error response.
     */
    public static ErrorResponse notFound(String detail, String instance) {
        return new ErrorResponse("about:blank", "Not Found", 404, detail, instance);
    }

    /**
     * Creates a 409 Conflict error response.
     */
    public static ErrorResponse conflict(String detail, String instance) {
        return new ErrorResponse("about:blank", "Conflict", 409, detail, instance);
    }

    /**
     * Creates a 500 Internal Server Error response.
     */
    public static ErrorResponse internalServerError(String detail, String instance) {
        return new ErrorResponse("about:blank", "Internal Server Error", 500, detail, instance);
    }
}
