package com.lanny.spring_security_template.tools.keygen;

import java.io.FileOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.util.Base64;

/**
 * ============================================================
 * RSA Key Pair Generator (Development / Local Use Only)
 * ============================================================
 *
 * <p>
 * Utility class to generate a 2048-bit RSA key pair in PKCS#8 PEM format,
 * compatible with Nimbus JOSE + JWT and Spring Security.
 * </p>
 *
 * <h2>SECURITY WARNING</h2>
 * <ul>
 * <li>This tool is intended for <b>local development and testing only</b></li>
 * <li>Keys generated by this class MUST NOT be used in production</li>
 * <li>Never commit generated private keys to version control</li>
 * </ul>
 *
 * <h2>Production usage</h2>
 * <p>
 * In production environments, RSA keys must be:
 * </p>
 * <ul>
 * <li>Generated and stored using a secure process (HSM, Vault, KMS, etc.)</li>
 * <li>Injected via filesystem, keystore, or secret manager</li>
 * <li>Rotated according to security policies</li>
 * </ul>
 *
 * <p>
 * This class is deliberately implemented as a standalone {@code main}
 * and must not be included in the application runtime.
 * </p>
 */

public class GenerateRsaKeys {
  public static void main(String[] args) throws Exception {
    KeyPairGenerator keyGen = KeyPairGenerator.getInstance("RSA");
    keyGen.initialize(2048);
    KeyPair pair = keyGen.generateKeyPair();

    Path keyDir = Paths.get("src/main/resources/keys");
    Files.createDirectories(keyDir);

    try (FileOutputStream out = new FileOutputStream(keyDir.resolve("rsa-private.pem").toFile())) {
      out.write("-----BEGIN PRIVATE KEY-----\n".getBytes());
      out.write(Base64.getMimeEncoder(64, "\n".getBytes()).encode(pair.getPrivate().getEncoded()));
      out.write("\n-----END PRIVATE KEY-----\n".getBytes());
    }

    try (FileOutputStream out = new FileOutputStream(keyDir.resolve("rsa-public.pem").toFile())) {
      out.write("-----BEGIN PUBLIC KEY-----\n".getBytes());
      out.write(Base64.getMimeEncoder(64, "\n".getBytes()).encode(pair.getPublic().getEncoded()));
      out.write("\n-----END PUBLIC KEY-----\n".getBytes());
    }

    System.out.println("✅ RSA key pair generated in src/main/resources/keys/");
  }
}
