package com.lanny.spring_security_template.infrastructure.security.handler;

import java.time.Instant;

/**
 * ============================================================
 * ApiError
 * ============================================================
 *
 * <p>
 * Immutable, client-safe error representation for HTTP responses.
 * </p>
 *
 * <h2>Purpose</h2>
 * <p>
 * Provides a standardized, security-conscious error payload
 * for all API responses generated by the infrastructure layer.
 * </p>
 *
 * <h2>Design rules</h2>
 * <ul>
 * <li>Error messages are generic and client-facing</li>
 * <li>No technical details or exception messages are exposed</li>
 * <li>No stack traces, class names or internal identifiers</li>
 * <li>CorrelationId enables request tracing across systems</li>
 * </ul>
 *
 * <h2>Security constraints</h2>
 * <ul>
 * <li>This object must never contain sensitive information</li>
 * <li>This is the only error shape exposed to API consumers</li>
 * <li>Internal exception details must be logged separately</li>
 * </ul>
 *
 * <h2>Usage</h2>
 * <p>
 * Typically created via {@code ApiErrorFactory} and returned by
 * filters or exception handlers within the security infrastructure.
 * </p>
 */
public record ApiError(
        Instant timestamp,
        int status,
        String error,
        String path,
        String correlationId) {
}
